name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: tunathu/thuthesis-test-env
    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: bash .github/workflows/install-packages.sh
    - name: Test thesis
      run: make main
    - name: Test doc
      run: make doc
    - name: l3build check
      run: make test
