name: CI
on:
  push:
    branches:
      - main
jobs:
  thesis-thesis:
    runs-on: ubuntu-latest
    container: tunathu/thuthesis-test-env
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: bash docs/thesis/thesis/scripts/install-packages.sh
      - name: Test thesis
        working-directory: docs/thesis/thesis
        run: make main
      - uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: docs/thesis/thesis/main.pdf
